# Generated by Django 4.1.7 on 2023-03-23 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_text", models.CharField(max_length=100)),
                ("price", models.TextField()),
                ("address", models.CharField(max_length=10)),
                ("order_date", models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
