# Generated by Django 4.1.7 on 2023-03-23 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="address",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(default=0),
        ),
    ]
