# Generated by Django 4.1.7 on 2023-03-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0002_alter_order_address_alter_order_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="price",
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
