# Generated by Django 4.1.7 on 2023-03-21 02:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("friend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="friend",
            old_name="frined_bigo",
            new_name="friend_bigo",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
    ]
